language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ayushjain95/docker-react  -f Dockerfile.dev .
script:
  - docker run -e CI=true ayushjain95/docker-react npm run test -- --coverage 
  #To make npm run test exit, without which, it would be waiting for us to press a button to proceed...