language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ayushjain95/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true ayushjain95/docker-react npm run test -- --coverage 
  #To make npm run test exit, without which, it would be waiting for us to press a button to proceed...

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-386256319483"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"